title: Clare Harshey
author: Clare Harshey
tagline: Grad student in Computational Linguistics with a passion for linguistics, NLP and problem solving.
description: Personal homepage for Clare Harshey
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
baseurl: ""
url: "http://harshey.me"


github_username: charshey
email: clarshey@gmail.com

favicon: "favicon.ico"
aboutme_photo: "me.jpg"

